name: Deploy WireGuard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install WireGuard
      run: sudo apt-get update && sudo apt-get install -y wireguard

    - name: Generate WireGuard keys
      run: |
        mkdir -p ~/wireguard-config
        wg genkey | tee ~/wireguard-config/server_privatekey | wg pubkey | tee ~/wireguard-config/server_publickey
        wg genkey | tee ~/wireguard-config/client_privatekey | wg pubkey | tee ~/wireguard-config/client_publickey

    - name: Configure WireGuard
      run: |
        SERVER_PRIVATE_KEY=$(cat ~/wireguard-config/server_privatekey)
        CLIENT_PUBLIC_KEY=$(cat ~/wireguard-config/client_publickey)
        echo "[Interface]
        PrivateKey = $SERVER_PRIVATE_KEY
        Address = 10.0.0.1/24
        ListenPort = 51820

        [Peer]
        PublicKey = $CLIENT_PUBLIC_KEY
        AllowedIPs = 10.0.0.2/32
        " | sudo tee /etc/wireguard/wg0.conf

    - name: Enable IP forwarding
      run: sudo sysctl -w net.ipv4.ip_forward=1

    - name: Configure iptables
      run: |
        sudo iptables -A FORWARD -i wg0 -j ACCEPT
        sudo iptables -A FORWARD -o wg0 -j ACCEPT
        sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        sudo apt-get install -y iptables-persistent
        sudo netfilter-persistent save

    - name: Start WireGuard
      run: sudo wg-quick up wg0

    - name: Save client configuration
      run: |
        CLIENT_PRIVATE_KEY=$(cat ~/wireguard-config/client_privatekey)
        SERVER_PUBLIC_KEY=$(cat ~/wireguard-config/server_publickey)
        echo "[Interface]
        PrivateKey = $CLIENT_PRIVATE_KEY
        Address = 10.0.0.2/24
        DNS = 1.1.1.1

        [Peer]
        PublicKey = $SERVER_PUBLIC_KEY
        Endpoint = <server_ip>:51820
        AllowedIPs = 0.0.0.0/0
        " > ~/wireguard-config/client.conf

    - name: Upload client configuration
      uses: actions/upload-artifact@v2
      with:
        name: client-config
        path: ~/wireguard-config/client.conf
